### ISSUE TITLE
`#[derive_where(skip(Clone, Debug))]` field attribute

### ISSUE THREAD

**Issue by daxpedda** [ModProg/derive-where#19]
We should add a `skip` field attribute à la zeroize.

**Comment by daxpedda** [comment]
I just realized that `skip` isn't useful except for `Hash` (very questionable) and `Zeroize`, right?

**Comment by ModProg** [comment]
> I just realized that `skip` isn't useful except for `Hash` (very questionable) and `Zeroize`, right?

What about Debug and Comparison, ecton definitely wants debug :D

**Comment by ModProg** [comment]
Tho this does also mean that there are actual good usecases to use this without the generics.

We could think about adding an implementation that just mimics standard in the trait bounds and only adds skip for now. 
I am hesitant to call this `derive_skip` tho. I don't know if there are other things than skip here, and this is also close to derivative (tho I'm not the biggest fan of all of derivative, so I would welcome it being in here :D).

Maybe `derive_extra` or `dervoe_restr` or `derive_attr` or `with` instead of `skip` `filtered`?.

I thought about using "two" arguments vs "on" : `(;Debug)` if you want to have no trait bounds, and `(Debug)` for the default ones. But this can very easily cause mistakes, so I don't think this is the way to go.

**Comment by daxpedda** [comment]
> What about Debug and Comparison, ecton definitely wants debug :D

I'm confused, how can you skip `Debug`? What should be there instead, panic? @ecton can you chime in on this please? Skipping comparison doesn't make sense to me as it sounds like a very custom implementation and should be done manually really.

To me skipping on `Zeroize` really is the only one making sense to me, as you maybe only want to skip certain fields and that's it, nothing wrong with that.

**Comment by ecton** [comment]
> I'm confused, how can you skip Debug?

[This is an example](https://github.com/khonsulabs/bonsaidb/blob/60f8dfa14e355b9df8a0d983821ebfede0d1296c/crates/bonsaidb-server/src/server.rs#L1916) of a type purely implemented to allow `CustomServer` to still be able to derive `Debug`. I would expect the fields to just be skipped, so that I could avoid introducing these thin types or implementing Debug manually for `CustomServer`.

> Skipping comparison doesn't make sense to me as it sounds like a very custom implementation and should be done manually really.

Everything is all about the programmer's intentions, not about the trait itself. Why should we only save programmer's time if the semantics of the trait imply that it should be possible?

My practical example is using a struct with `Hash`, where I want to skip a field not only for Hashing purposes, but also for Eq/PartialEq purposes. Perhaps the extra fields are cache-like fields, or they are other metadata that don't impact the actual unique-ness of using the type as a "key" in a HashMap -- potentially the primary reason for that type.

You can argue about semantics of whether or not it's correct -- but it is useful.

**Comment by daxpedda** [comment]
> > I'm confused, how can you skip Debug?
> 
> [This is an example](https://github.com/khonsulabs/bonsaidb/blob/60f8dfa14e355b9df8a0d983821ebfede0d1296c/crates/bonsaidb-server/src/server.rs#L1916) of a type purely implemented to allow `CustomServer` to still be able to derive `Debug`. I would expect the fields to just be skipped, so that I could avoid introducing these thin types or implementing Debug manually for `CustomServer`.

This is very obvious, I was distracted with `enum` variants that you can't just skip. Thanks!
> > Skipping comparison doesn't make sense to me as it sounds like a very custom implementation and should be done manually really.
> 
> Everything is all about the programmer's intentions, not about the trait itself. Why should we only save programmer's time if the semantics of the trait imply that it should be possible?
> 
> My practical example is using a struct with `Hash`, where I want to skip a field not only for Hashing purposes, but also for Eq/PartialEq purposes. Perhaps the extra fields are cache-like fields, or they are other metadata that don't impact the actual unique-ness of using the type as an entry in a HashSet -- potentially the primary reason for that type.
> 
> You can argue about semantics of whether or not it's correct -- but it is useful.

My concern was that it introduces some level of non-transparency. The point of the library for me is to reduce code-duplication mainly, not necessarily offer some shortcuts.

I felt like if you have a custom implementation for `PartialEq` or `Ord/PartialOrd`, it would be sensible to just write it out, unless of course you start repeating yourself.

But if you say it's useful to you, that's enough of a use-case to me. So yeah, let's do it!

**Comment by ModProg** [comment]
> This is very obvious, I was distracted with enum variants that you can't just skip. Thanks!

For enum variants, we could add `skip_inner`.

**Comment by daxpedda** [comment]
That is a very good idea! Alternatively one could just explicitly skip every field inside, but a shortcut to that with `skip_inner` sounds great.

**Comment by daxpedda** [comment]
I was just working on that, is there a case where we really want to completely skip all fields in an enum variant? Or generally, is there ever a case where we want to skip all fields?
@ecton if you can chime in here too please.

**Comment by ecton** [comment]
> I was just working on that, is there a case where we really want to completely skip all fields in an enum variant? Or generally, is there ever a case where we want to skip all fields?

All fields/tuple values in a single enum variant? Yes -- BonsaiDb's Request and Response types. `Request::<T>::Api(T)` where T isn't Debug, I want to implement Debug. While technically BonsaiDb uses the tuple-style variant, I see no difference from a single-element tuple and a single named field of the same type -- i.e., `Request::<T>::Api { api_request }`

If I misunderstood the question, can you give an example of what situation you're asking about?

**Comment by daxpedda** [comment]
No that is exactly what I was asking, somehow my brain just doesn't want to wrap it's mind around this. Skipping all fields should definitely be possible and is useful!
Thanks again.
